import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import { ThemeProvider } from 'next-themes';
import { ModeToggle } from '@/components/mode-toggle';
import { Toaster } from '@/components/ui/toaster';
// import { useServerSession } from '@/lib/useServerSession';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'YOUR NOTES',
  description: 'Generated by you',
};

// export async function generateMetadata(): Promise<Metadata> {
//   const { user } = await useServerSession();

//   return {
//     title: user.username,
//   };
// }

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={inter.className}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <div className="fixed top-2 right-2">
            <ModeToggle />
          </div>
          {children}
          <Toaster />
        </ThemeProvider>
      </body>
    </html>
  );
}
